export { default as Navbar } from './Navbar/Navbar'
export { default as Category } from './Category/Category'
export { default as Plato } from './Plato/Plato'
export { default as Carrito } from './Carrito/Carrito'
export { default as Banner } from './Banner/Banner'
export { default as BgImage } from './BgImage/BgImage'
export { default as Overlay } from './Overlay/Overlay'
