const stockPhoto = '../images/carrito1.jpg'

const saporiDiFamigliaFotos = {
    logo: '../images/SaporiDiFamiglia/logo.jpeg',
    raviolones1: '../images/SaporiDiFamiglia/raviolones1.jpeg',
    raviolones2: '../images/SaporiDiFamiglia/raviolones2.jpeg',
    sorrentinos1: '../images/SaporiDiFamiglia/sorrentinos1.jpeg',
    sorrentinos2: '../images/SaporiDiFamiglia/sorrentinos2.jpeg',
    sorrentinos3: '../images/SaporiDiFamiglia/sorrentinos3.jpeg',
    sorrentinos4: '../images/SaporiDiFamiglia/sorrentinos4.jpeg',
    tallarines: '../images/SaporiDiFamiglia/tallarines.jpeg',
    ñoquisTricolor: '../images/SaporiDiFamiglia/ñoquisTricolor.jpeg',
}
const elBululu = {
    arepas1: '../images/ElBululu/arepas1.jpeg',
    arepas2: '../images/ElBululu/arepas2.jpeg',
    arepas3: '../images/ElBululu/arepas3.jpeg',
    tequeños1: '../images/ElBululu/tequeños1.jpeg',
    tequeños2: '../images/ElBululu/tequeños2.jpeg',
}
const poppi = {
    empanadas1: '../images/Poppi/empanadas1.jpeg',
    pizza1: '../images/Poppi/pizza1.jpeg',
    pizza2: '../images/Poppi/pizza2.jpeg',
    pizza3: '../images/Poppi/pizza3.jpeg',
}

const gaseosas = '../images/bebidas/lineaCoca.jpg'
const descGaseosas = 'Gaseosas 500ml linea Coca-Cola. Consultar disponibilidad'
const aguaMineral = '../images/bebidas/aguaMineral.jpg'
const descAgua = 'Agua mineral 500ml. Consultar disponibilidad'
const vino = '../images/bebidas/vino.png'
const descVino = 'Consultar variedades'

const dataCarritos = [
    {
        id: 0,
        nombre: 'Sativa',
        foto: stockPhoto,
        desc: `Sandwich Bife de Chorizo y Choripan`,
        userInsta: '',
        idFace: '',
        numWpp: '',
        carta: {
            principales: [
                {
                    id: 0,
                    nombre: 'Sandwich bife chorizo',
                    foto: stockPhoto,
                    desc: 'Sandwich bife chorizo',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Choripan',
                    foto: stockPhoto,
                    desc: 'Choripan',
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Pollo crispa',
                    foto: stockPhoto,
                    desc: 'Pollo crispa',
                    precio: '$$$$',
                },
            ],
            acompañamientos: [
                {
                    id: 0,
                    nombre: 'Papas 1',
                    foto: stockPhoto,
                    desc: 'Descripcion papas 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Papas 2',
                    foto: stockPhoto,
                    desc: 'Descripcion papas 2',
                    precio: '$$$$',
                },
            ],
            bebidas: [
                {
                    id: 0,
                    nombre: 'Gaseosa',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Agua Mineral',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
            ],
        },
    },
    {
        id: 1,
        cerveceria: true,
        nombre: 'Garinger',
        foto: stockPhoto,
        desc: 'Cerveza Artesanal',
        userInsta: '',
        idFace: '',
        numWpp: '',
        carta: {
            cervezas: [
                {
                    id: 0,
                    nombre: 'Cerveza 1',
                    foto: stockPhoto,
                    desc: 'Descripcion cerveza 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Cerveza 2',
                    foto: stockPhoto,
                    desc: 'Descripcion cerveza 2',
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Cerveza 3',
                    foto: stockPhoto,
                    desc: 'Descripcion cerveza 3',
                    precio: '$$$$',
                },
            ],
        },
    },
    {
        id: 2,
        nombre: 'Station',
        foto: stockPhoto,
        desc: 'Panchos y Ciabatta',
        userInsta: '',
        idFace: '',
        numWpp: '',
        carta: {
            principales: [
                {
                    id: 0,
                    nombre: 'Pancho 1',
                    foto: stockPhoto,
                    desc: 'Descripcion pancho 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Pancho 2',
                    foto: stockPhoto,
                    desc: 'Descripcion pancho 2',
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Ciabatta',
                    foto: stockPhoto,
                    desc: 'Descripcion ciabatta',
                    precio: '$$$$',
                },
            ],
            acompañamientos: [
                {
                    id: 0,
                    nombre: 'Papas 1',
                    foto: stockPhoto,
                    desc: 'Descripcion papas 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Papas 2',
                    foto: stockPhoto,
                    desc: 'Descripcion papas 2',
                    precio: '$$$$',
                },
            ],
            bebidas: [
                {
                    id: 0,
                    nombre: 'Gaseosa',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Agua Mineral',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
            ],
        },
    },
    {
        id: 3,
        nombre: 'Sapore Di Famiglia',
        foto: saporiDiFamigliaFotos.logo,
        desc: 'Pastas Caseras',
        userInsta: '_saporidifamiglia_',
        idFace: '',
        numWpp: [5492664020989, 5492664173795],
        carta: {
            sorrentinos: [
                {
                    id: 0,
                    nombre: 'Muzarella y jamon',
                    foto: saporiDiFamigliaFotos.sorrentinos1,
                    desc: 'Sorrentinos de Muzarella y jamon',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Muzarella, tomate y albahaca',
                    foto: saporiDiFamigliaFotos.sorrentinos2,
                    desc: 'Sorrentinos de Muzarella, tomate y albahaca',
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Muzarella y cantimpalo',
                    foto: saporiDiFamigliaFotos.sorrentinos3,
                    desc: 'Sorrentinos de Muzarella y cantimpalo',
                    precio: '$$$$',
                },
                {
                    id: 3,
                    nombre: 'Muzarella, rucula y jamon crudo',
                    foto: saporiDiFamigliaFotos.sorrentinos4,
                    desc: 'Sorrentinos de Muzarella, rucula y jamon crudo',
                    precio: '$$$$',
                },
            ],
            raviolones: [
                {
                    id: 0,
                    nombre: 'Muzarella, verdeo y jamon crudo',
                    foto: saporiDiFamigliaFotos.raviolones1,
                    desc: 'Raviolones de Muzarella, verdeo y jamon crudo',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Cuatro quesos',
                    foto: saporiDiFamigliaFotos.raviolones2,
                    desc: 'Raviolones de Cuatro quesos',
                    precio: '$$$$',
                },
            ],
            ñoquis: [
                {
                    id: 0,
                    nombre: 'De papa',
                    foto: saporiDiFamigliaFotos.ñoquisTricolor,
                    desc: 'Ñoquis de papa',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Tricolor',
                    foto: saporiDiFamigliaFotos.ñoquisTricolor,
                    desc: 'Ñoquis tricolor',
                    precio: '$$$$',
                },
            ],
            tallarines: [
                {
                    id: 0,
                    nombre: 'Tallarines',
                    foto: saporiDiFamigliaFotos.tallarines,
                    desc: 'Tallarines',
                    precio: '$$$$',
                },
            ],
            salsas: [
                {
                    id: 0,
                    nombre: 'Salsa 1',
                    foto: saporiDiFamigliaFotos.sorrentinos1,
                    desc: 'Descripcion salsa 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Salsa 2',
                    foto: saporiDiFamigliaFotos.sorrentinos2,
                    desc: 'Descripcion salsa 2',
                    precio: '$$$$',
                },
            ],
            bebidas: [
                {
                    id: 0,
                    nombre: 'Gaseosa',
                    foto: gaseosas,
                    desc: descGaseosas,
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Agua Mineral',
                    foto: aguaMineral,
                    desc: descAgua,
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Vino 1',
                    foto: vino,
                    desc: descVino,
                    precio: '$$$$',
                },
            ],
        },
    },
    {
        id: 4,
        nombre: 'Berraco',
        foto: stockPhoto,
        desc: 'Lomitos y Milanesas',
        userInsta: '',
        idFace: '',
        numWpp: '',
        carta: {
            sandwiches: [
                {
                    id: 0,
                    nombre: 'Sandwich Mila',
                    foto: stockPhoto,
                    desc: 'Descripcion sandwich mila',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Sandwich Veggie',
                    foto: stockPhoto,
                    desc: 'Descripcion sandwich veggie',
                    precio: '$$$$',
                },
            ],
            acompañamientos: [
                {
                    id: 0,
                    nombre: 'Papas 1',
                    foto: stockPhoto,
                    desc: 'Descripcion papas 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Papas 2',
                    foto: stockPhoto,
                    desc: 'Descripcion papas 2',
                    precio: '$$$$',
                },
            ],
            bebidas: [
                {
                    id: 0,
                    nombre: 'Gaseosa',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Agua Mineral',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
            ],
        },
    },
    {
        id: 5,
        nombre: 'Buena Faena',
        foto: stockPhoto,
        desc: 'Pulled Pork y Hamburguesas Gourmet',
        userInsta: '',
        idFace: '',
        numWpp: '',
        carta: {
            hamburguesas: [
                {
                    id: 0,
                    nombre: 'Gourmet',
                    foto: stockPhoto,
                    desc: 'Descripcion hamburguesa gourmet',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Pork',
                    foto: stockPhoto,
                    desc: 'Descripcion hamburguesa pork',
                    precio: '$$$$',
                },
            ],
            hotdogs: [
                {
                    id: 0,
                    nombre: 'Chucrut',
                    foto: stockPhoto,
                    desc: 'Descripcion hotdog chucrut',
                },
            ],
            bebidas: [
                {
                    id: 0,
                    nombre: 'Gaseosa',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Agua Mineral',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
            ],
        },
    },
    {
        id: 6,
        cerveceria: true,
        nombre: 'Chunkana',
        foto: stockPhoto,
        desc: 'Cerveza Artesanal',
        userInsta: '',
        idFace: '',
        numWpp: '',
        carta: {
            cerveza: [
                {
                    id: 0,
                    nombre: 'Cerveza 1',
                    foto: stockPhoto,
                    desc: 'Descripcion cerveza 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Cerveza 2',
                    foto: stockPhoto,
                    desc: 'Descripcion cerveza 2',
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Cerveza 3',
                    foto: stockPhoto,
                    desc: 'Descripcion cerveza 3',
                    precio: '$$$$',
                },
            ],
        },
    },
    {
        id: 7,
        nombre: 'El Bululu',
        foto: stockPhoto,
        desc: 'Comida Venezolana y Helado Soft',
        userInsta: 'elbululu.ve',
        idFace: '',
        numWpp: [5492664848269, 5491154579188],
        carta: {
            arepas: [
                {
                    id: 0,
                    nombre: 'Mechada',
                    foto: elBululu.arepas1,
                    desc: 'Arepa hecha con harina de maíz sin TACC, con relleno de carne desmenuzada con queso',
                    precio: '$$$$$$',
                },
                {
                    id: 1,
                    nombre: 'Reina pepiada',
                    foto: elBululu.arepas2,
                    desc: 'Arepa hecha con harina de maíz sin TACC, con relleno de pollo desmenuzado con aderezo de palta y queso',
                    precio: '$$$$$$',
                },
                {
                    id: 2,
                    nombre: 'Pollo al Grill',
                    foto: elBululu.arepas3,
                    desc: 'Arepa hecha con harina de maíz sin TACC, con relleno de pollo a la plancha con jamón y queso',
                    precio: '$$$$$$',
                },
                {
                    id: 3,
                    nombre: 'Veggie',
                    foto: elBululu.arepas1,
                    desc: 'Arepa hecha con harina de maíz sin TACC, con relleno de vegetales salteados y queso',
                    precio: '$$$$$$',
                },
            ],
            tequeños: [
                {
                    id: 0,
                    nombre: 'Queso',
                    foto: elBululu.tequeños1,
                    desc: 'deditos de queso blanco envueltos en harina de trigo',
                    precio: '$$$$$$',
                },
                {
                    id: 1,
                    nombre: 'Chocolate',
                    foto: elBululu.tequeños2,
                    desc: 'deditos de chocolate envueltos en harina de trigo',
                    precio: '$$$$$$',
                },
            ],
            bebidas: [
                {
                    id: 0,
                    nombre: 'Gaseosa',
                    foto: gaseosas,
                    desc: descGaseosas,
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Agua Mineral',
                    foto: aguaMineral,
                    desc: descAgua,
                    precio: '$$$$',
                },
            ],
        },
    },
    {
        id: 8,
        nombre: 'La Patrona',
        foto: stockPhoto,
        desc: 'Comida Mexicana',
        userInsta: '',
        idFace: '',
        numWpp: '',
        carta: {
            tacos: [
                {
                    id: 0,
                    nombre: 'Carne',
                    foto: stockPhoto,
                    desc: 'Descripcion tacos carne',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Veggie',
                    foto: stockPhoto,
                    desc: 'Descripcion tacos veggie',
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Quesadillas',
                    foto: stockPhoto,
                    desc: 'Descripcion quesadillas',
                    precio: '$$$$',
                },
            ],
            acompañamientos: [
                {
                    id: 0,
                    nombre: 'Nachos',
                    foto: stockPhoto,
                    desc: 'Descripcion nachos',
                    precio: '$$$$',
                },
            ],
            bebidas: [
                {
                    id: 0,
                    nombre: 'Gaseosa',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Agua Mineral',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
            ],
        },
    },
    {
        id: 9,
        nombre: 'Poppi',
        foto: stockPhoto,
        desc: 'Pizzas y Empanadas',
        userInsta: '',
        idFace: '',
        numWpp: '',
        carta: {
            pizzas: [
                {
                    id: 0,
                    nombre: 'Napolitana',
                    foto: poppi.pizza1,
                    desc: 'Pizza de napolitana',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Roquefort',
                    foto: poppi.pizza2,
                    desc: 'Pizza de roquefort',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Anchoas',
                    foto: poppi.pizza3,
                    desc: 'Pizza de anchoas',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Huevo',
                    foto: poppi.pizza1,
                    desc: 'Pizza de huevo',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Jamon y morron',
                    foto: poppi.pizza2,
                    desc: 'Pizza de Jamon y morron',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Vegetales',
                    foto: poppi.pizza3,
                    desc: 'Pizza de Vegetales',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Rúcula',
                    foto: poppi.pizza1,
                    desc: 'Pizza de Rúcula',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Champiñones',
                    foto: poppi.pizza2,
                    desc: 'Pizza de Champiñones',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Calabresa',
                    foto: poppi.pizza3,
                    desc: 'Pizza de Calabresa',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Palmitos',
                    foto: poppi.pizza1,
                    desc: 'Pizza de Palmitos',
                    precio: '$$$$',
                },
            ],
            empanadas: [
                {
                    id: 0,
                    nombre: 'Carne',
                    foto: poppi.empanadas1,
                    desc: 'Descripcion Carne',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Pollo',
                    foto: poppi.empanadas1,
                    desc: 'Descripcion Pollo',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Capresse',
                    foto: poppi.empanadas1,
                    desc: 'Descripcion Capresse',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Jamón y queso',
                    foto: poppi.empanadas1,
                    desc: 'Descripcion Jamón y queso',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Vegetales',
                    foto: poppi.empanadas1,
                    desc: 'Descripcion Vegetales',
                    precio: '$$$$',
                },
            ],
            ensaladas: [
                {
                    id: 0,
                    nombre: 'Ensalada 1',
                    foto: stockPhoto,
                    desc: 'Descripcion Ensalada 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Ensalada 2',
                    foto: stockPhoto,
                    desc: 'Descripcion Ensalada 2',
                    precio: '$$$$',
                },
            ],
            papas: [
                {
                    id: 0,
                    nombre: 'Papas 1',
                    foto: stockPhoto,
                    desc: 'Descripcion Papas 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Papas 2',
                    foto: stockPhoto,
                    desc: 'Descripcion Papas 2',
                    precio: '$$$$',
                },
            ],
            postres: [
                {
                    id: 0,
                    nombre: 'Tiramisu',
                    foto: stockPhoto,
                    desc: 'Descripcion Tiramisu',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Chocotorta',
                    foto: stockPhoto,
                    desc: 'Descripcion Chocotorta',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Cheesecake',
                    foto: stockPhoto,
                    desc: 'Descripcion Cheesecake',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Flan casero',
                    foto: stockPhoto,
                    desc: 'Descripcion Flan casero',
                    precio: '$$$$',
                },
            ],
            bebidas: [
                {
                    id: 0,
                    nombre: 'Gaseosa',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Agua Mineral',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
            ],
        },
    },
    {
        id: 10,
        nombre: 'Dulzuras Detuti',
        foto: stockPhoto,
        desc: 'Garrapiñadas y Turrones',
        userInsta: '',
        idFace: '',
        numWpp: '',
        carta: {
            garrapiñadas: [
                {
                    id: 0,
                    nombre: 'Garrapiñada Mani',
                    foto: stockPhoto,
                    desc: 'Descripcion garrapiñada Mani',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Garrapiñada Girasol',
                    foto: stockPhoto,
                    desc: 'Descripcion garrapiñada girasol',
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Garrapiñada Nuez',
                    foto: stockPhoto,
                    desc: 'Descripcion garrapiñada Nuez',
                    precio: '$$$$',
                },
                {
                    id: 3,
                    nombre: 'Garrapiñada Almendra',
                    foto: stockPhoto,
                    desc: 'Descripcion garrapiñada Almendra',
                    precio: '$$$$',
                },
                {
                    id: 4,
                    nombre: 'Garrapiñada Castañas de Caju',
                    foto: stockPhoto,
                    desc: 'Descripcion garrapiñada Castañas de Caju',
                    precio: '$$$$',
                },
                {
                    id: 5,
                    nombre: 'Garrapiñada Avellana',
                    foto: stockPhoto,
                    desc: 'Descripcion garrapiñada Avellana',
                    precio: '$$$$',
                },
            ],
            turrones_blandos: [
                {
                    id: 0,
                    nombre: 'Mani triturado',
                    foto: stockPhoto,
                    desc: 'Descripcion Mani triturado',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Mani y Coco Rallado',
                    foto: stockPhoto,
                    desc: 'Descripcion Mani y Coco Rallado',
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Mani y Chocolate Rallado',
                    foto: stockPhoto,
                    desc: 'Descripcion Mani y Chocolate Rallado',
                    precio: '$$$$',
                },
            ],
        },
    },
]

export default dataCarritos
