const stockPhoto = '../images/carrito1.jpg'

const dataCarritos = [
    {
        id: 0,
        nombre: 'Sativa',
        foto: stockPhoto,
        desc: `descripcion Sativa`,
        carta: {
            principales: [
                {
                    id: 0,
                    nombre: 'Sandwich bife chorizo',
                    foto: stockPhoto,
                    desc: 'Sandwich bife chorizo',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Choripan',
                    foto: stockPhoto,
                    desc: 'Choripan',
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Pollo crispa',
                    foto: stockPhoto,
                    desc: 'Pollo crispa',
                    precio: '$$$$',
                },
            ],
            acompañamientos: [
                {
                    id: 0,
                    nombre: 'Papas 1',
                    foto: stockPhoto,
                    desc: 'Descripcion papas 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Papas 2',
                    foto: stockPhoto,
                    desc: 'Descripcion papas 2',
                    precio: '$$$$',
                },
            ],
            bebidas: [
                {
                    id: 0,
                    nombre: 'Gaseosa',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Agua Mineral',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
            ],
        },
    },
    {
        id: 1,
        nombre: 'Garinger',
        foto: stockPhoto,
        desc: 'Descripcion Garinger',
        carta: {
            cervezas: [
                {
                    id: 0,
                    nombre: 'Cerveza 1',
                    foto: stockPhoto,
                    desc: 'Descripcion cerveza 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Cerveza 2',
                    foto: stockPhoto,
                    desc: 'Descripcion cerveza 2',
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Cerveza 3',
                    foto: stockPhoto,
                    desc: 'Descripcion cerveza 3',
                    precio: '$$$$',
                },
            ],
        },
    },
    {
        id: 2,
        nombre: 'Station',
        foto: stockPhoto,
        desc: 'Descripcion Station',
        carta: {
            principales: [
                {
                    id: 0,
                    nombre: 'Pancho 1',
                    foto: stockPhoto,
                    desc: 'Descripcion pancho 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Pancho 2',
                    foto: stockPhoto,
                    desc: 'Descripcion pancho 2',
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Ciabatta',
                    foto: stockPhoto,
                    desc: 'Descripcion ciabatta',
                    precio: '$$$$',
                },
            ],
            acompañamientos: [
                {
                    id: 0,
                    nombre: 'Papas 1',
                    foto: stockPhoto,
                    desc: 'Descripcion papas 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Papas 2',
                    foto: stockPhoto,
                    desc: 'Descripcion papas 2',
                    precio: '$$$$',
                },
            ],
            bebidas: [
                {
                    id: 0,
                    nombre: 'Gaseosa',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Agua Mineral',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
            ],
        },
    },
    {
        id: 3,
        nombre: 'Sapore Di Famiglia',
        foto: stockPhoto,
        desc: 'Descripcion Sapore Di Famiglia',
        carta: {
            pastas: [
                {
                    id: 0,
                    nombre: 'Pasta 1',
                    foto: stockPhoto,
                    desc: 'Descripcion pasta 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Pasta 2',
                    foto: stockPhoto,
                    desc: 'Descripcion pasta 2',
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Pasta 3',
                    foto: stockPhoto,
                    desc: 'Descripcion pasta 3',
                    precio: '$$$$',
                },
            ],
            bebidas: [
                {
                    id: 0,
                    nombre: 'Gaseosa',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Agua Mineral',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Vino 1',
                    foto: stockPhoto,
                    desc: 'Descripcion Vino 1',
                    precio: '$$$$',
                },
            ],
        },
    },
    {
        id: 4,
        nombre: 'Berraco',
        foto: stockPhoto,
        desc: 'Descripcion Berraco',
        carta: {
            sandwiches: [
                {
                    id: 0,
                    nombre: 'Sandwich Mila',
                    foto: stockPhoto,
                    desc: 'Descripcion sandwich mila',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Sandwich Veggie',
                    foto: stockPhoto,
                    desc: 'Descripcion sandwich veggie',
                    precio: '$$$$',
                },
            ],
            acompañamientos: [
                {
                    id: 0,
                    nombre: 'Papas 1',
                    foto: stockPhoto,
                    desc: 'Descripcion papas 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Papas 2',
                    foto: stockPhoto,
                    desc: 'Descripcion papas 2',
                    precio: '$$$$',
                },
            ],
            bebidas: [
                {
                    id: 0,
                    nombre: 'Gaseosa',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Agua Mineral',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
            ],
        },
    },
    {
        id: 5,
        nombre: 'Buena Faena',
        foto: stockPhoto,
        desc: 'Descripcion Buena Faena',
        carta: {
            hamburguesas: [
                {
                    id: 0,
                    nombre: 'Gourmet',
                    foto: stockPhoto,
                    desc: 'Descripcion hamburguesa gourmet',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Pork',
                    foto: stockPhoto,
                    desc: 'Descripcion hamburguesa pork',
                    precio: '$$$$',
                },
            ],
            hotdogs: [
                {
                    id: 0,
                    nombre: 'Chucrut',
                    foto: stockPhoto,
                    desc: 'Descripcion hotdog chucrut',
                },
            ],
            bebidas: [
                {
                    id: 0,
                    nombre: 'Gaseosa',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Agua Mineral',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
            ],
        },
    },
    {
        id: 6,
        nombre: 'Chunkana',
        foto: stockPhoto,
        desc: 'Descripcion chunkana',
        carta: {
            cerveza: [
                {
                    id: 0,
                    nombre: 'Cerveza 1',
                    foto: stockPhoto,
                    desc: 'Descripcion cerveza 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Cerveza 2',
                    foto: stockPhoto,
                    desc: 'Descripcion cerveza 2',
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Cerveza 3',
                    foto: stockPhoto,
                    desc: 'Descripcion cerveza 3',
                    precio: '$$$$',
                },
            ],
        },
    },
    {
        id: 7,
        nombre: 'El Bululu',
        foto: stockPhoto,
        desc: 'Descripcion el bululu',
        carta: {
            arepas: [
                {
                    id: 0,
                    nombre: 'Arepa 1',
                    foto: stockPhoto,
                    desc: 'Descripcion Arepa 1',
                    precio: '$$$$$$',
                },
                {
                    id: 1,
                    nombre: 'Arepa 2',
                    foto: stockPhoto,
                    desc: 'Descripcion Arepa 2',
                    precio: '$$$$$$',
                },
                {
                    id: 2,
                    nombre: 'Arepa 3',
                    foto: stockPhoto,
                    desc: 'Descripcion Arepa 3',
                    precio: '$$$$$$',
                },
            ],
            tequeños: [
                {
                    id: 0,
                    nombre: 'Queso',
                    foto: stockPhoto,
                    desc: 'Descripcion queso',
                    precio: '$$$$$$',
                },
                {
                    id: 1,
                    nombre: 'Chocolate',
                    foto: stockPhoto,
                    desc: 'Descripcion chocolate',
                    precio: '$$$$$$',
                },
            ],
            bebidas: [
                {
                    id: 0,
                    nombre: 'Gaseosa',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Agua Mineral',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
            ],
        },
    },
    {
        id: 8,
        nombre: 'La Patrona',
        foto: stockPhoto,
        desc: 'Descripcion la patrona',
        carta: {
            tacos: [
                {
                    id: 0,
                    nombre: 'Carne',
                    foto: stockPhoto,
                    desc: 'Descripcion tacos carne',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Veggie',
                    foto: stockPhoto,
                    desc: 'Descripcion tacos veggie',
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Quesadillas',
                    foto: stockPhoto,
                    desc: 'Descripcion quesadillas',
                    precio: '$$$$',
                },
            ],
            acompañamientos: [
                {
                    id: 0,
                    nombre: 'Nachos',
                    foto: stockPhoto,
                    desc: 'Descripcion nachos',
                    precio: '$$$$',
                },
            ],
            bebidas: [
                {
                    id: 0,
                    nombre: 'Gaseosa',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Agua Mineral',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
            ],
        },
    },
    {
        id: 9,
        nombre: 'Poppi',
        foto: stockPhoto,
        desc: 'Descripcion poppi',
        carta: {
            pizzas: [
                {
                    id: 0,
                    nombre: 'Pizza 1',
                    foto: stockPhoto,
                    desc: 'Descripcion pizza 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Pizza 2',
                    foto: stockPhoto,
                    desc: 'Descripcion pizza 2',
                    precio: '$$$$',
                },
            ],
            empanadas: [
                {
                    id: 0,
                    nombre: 'Empanada 1',
                    foto: stockPhoto,
                    desc: 'Descripcion Empanada 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Empanada 2',
                    foto: stockPhoto,
                    desc: 'Descripcion Empanada 2',
                    precio: '$$$$',
                },
            ],
            ensaladas: [
                {
                    id: 0,
                    nombre: 'Ensalada 1',
                    foto: stockPhoto,
                    desc: 'Descripcion Ensalada 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Ensalada 2',
                    foto: stockPhoto,
                    desc: 'Descripcion Ensalada 2',
                    precio: '$$$$',
                },
            ],
            postres: [
                {
                    id: 0,
                    nombre: 'Postre 1',
                    foto: stockPhoto,
                    desc: 'Descripcion Postre 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Postre 2',
                    foto: stockPhoto,
                    desc: 'Descripcion Postre 2',
                    precio: '$$$$',
                },
            ],
            papas: [
                {
                    id: 0,
                    nombre: 'Papas 1',
                    foto: stockPhoto,
                    desc: 'Descripcion papas 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Papas 2',
                    foto: stockPhoto,
                    desc: 'Descripcion papas 2',
                    precio: '$$$$',
                },
            ],
            bebidas: [
                {
                    id: 0,
                    nombre: 'Gaseosa',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Agua Mineral',
                    foto: stockPhoto,
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
            ],
        },
    },
    {
        id: 10,
        nombre: 'Dulzuras Detuti',
        foto: stockPhoto,
        desc: 'Descripcion dulzuras detuti',
        carta: {
            garrapiñadas: [
                {
                    id: 0,
                    nombre: 'Garrapiñada Mani',
                    foto: stockPhoto,
                    desc: 'Descripcion garrapiñada Mani',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Garrapiñada Girasol',
                    foto: stockPhoto,
                    desc: 'Descripcion garrapiñada girasol',
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Garrapiñada Nuez',
                    foto: stockPhoto,
                    desc: 'Descripcion garrapiñada Nuez',
                    precio: '$$$$',
                },
                {
                    id: 3,
                    nombre: 'Garrapiñada Almendra',
                    foto: stockPhoto,
                    desc: 'Descripcion garrapiñada Almendra',
                    precio: '$$$$',
                },
                {
                    id: 4,
                    nombre: 'Garrapiñada Castañas de Caju',
                    foto: stockPhoto,
                    desc: 'Descripcion garrapiñada Castañas de Caju',
                    precio: '$$$$',
                },
                {
                    id: 5,
                    nombre: 'Garrapiñada Avellana',
                    foto: stockPhoto,
                    desc: 'Descripcion garrapiñada Avellana',
                    precio: '$$$$',
                },
            ],
            turrones_blandos: [
                {
                    id: 0,
                    nombre: 'Mani triturado',
                    foto: stockPhoto,
                    desc: 'Descripcion Mani triturado',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Mani y Coco Rallado',
                    foto: stockPhoto,
                    desc: 'Descripcion Mani y Coco Rallado',
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Mani y Chocolate Rallado',
                    foto: stockPhoto,
                    desc: 'Descripcion Mani y Chocolate Rallado',
                    precio: '$$$$',
                },
            ],
        },
    },
]

export default dataCarritos
