const sapore = {
    logo: '../images/Sapore/logo.jpeg',
    raviolones1: '../images/Sapore/raviolones1.jpeg',
    raviolones2: '../images/Sapore/raviolones2.jpeg',
    sorrentinos1: '../images/Sapore/sorrentinos1.jpeg',
    sorrentinos2: '../images/Sapore/sorrentinos2.jpeg',
    sorrentinos3: '../images/Sapore/sorrentinos3.jpeg',
    sorrentinos4: '../images/Sapore/sorrentinos4.jpeg',
    tallarines: '../images/Sapore/tallarines.jpeg',
    ñoquisTricolor: '../images/Sapore/ñoquisTricolor.jpeg',
    vino: '../images/Sapore/vino.png',
}
const elBululu = {
    logo: '../images/ElBululu/logo.jpeg',
    arepas1: '../images/ElBululu/arepas1.jpeg',
    arepas2: '../images/ElBululu/arepas2.jpeg',
    arepas3: '../images/ElBululu/arepas3.jpeg',
    tequeños1: '../images/ElBululu/tequeños1.jpeg',
    tequeños2: '../images/ElBululu/tequeños2.jpeg',
}
const poppi = {
    empanadas1: '../images/Poppi/empanadas1.jpeg',
    pizza1: '../images/Poppi/pizza1.jpeg',
    pizza2: '../images/Poppi/pizza2.jpeg',
    pizza3: '../images/Poppi/pizza3.jpeg',
}
const berraco = {
    logo: '../images/Berraco/logo.jpeg',
    veggie: ' ../images/Berraco/veggie.jpeg',
    veggieRecortada: ' ../images/Berraco/veggieRecortada.jpeg',
    milanesa: '../images/Berraco/milanesa.jpeg',
    milanesaRecortada: '../images/Berraco/milanesaRecortada.jpeg',
    lomito: '../images/Berraco/lomito.jpeg',
    lomitoRecortado: '../images/Berraco/lomitoRecortado.jpeg',
    papasFritas: '../images/Berraco/papasFritas.jpeg',
}
const detuti = {
    logoColor: '../images/Detuti/logoColor.jpeg',
    logoBlanco: '../images/Detuti/logoBlanco.jpeg',
}
const sativa = {
    logoColor: '../images/Sativa/logoColor.jpeg',
    logoBlanco: '../images/Sativa/logoBlanco.jpeg',
    logoColorRecortada: '../images/Sativa/logoColorRecortada.jpeg',
    logoBlancoRecortada: '../images/Sativa/logoBlancoRecortada.jpeg',
}
const patrona = {
    logo: '../images/LaPatrona/logo.jpeg',
}

const shared = {
    gaseosas: {
        id: 0,
        nombre: 'Gaseosa',
        foto: '../images/bebidas/lineaCoca.jpg',
        desc: 'Gaseosas 500ml linea Coca-Cola. Consultar disponibilidad',
        precio: '$$$$',
    },
    agua_mineral: {
        id: 1,
        nombre: 'Agua Mineral',
        foto: '../images/bebidas/aguaMineral.jpg',
        desc: 'Agua mineral 500ml. Consultar disponibilidad',
        precio: '$$$$',
    },
}

const dataCarritos = [
    {
        id: 0,
        nombre: 'Sativa',
        foto: sativa.logoColorRecortada,
        desc: `Sandwich Bife de Chorizo y Choripan`,
        userInsta: '',
        idFace: '',
        numWpp: '',
        carta: {
            principales: [
                {
                    id: 0,
                    nombre: 'Sandwich bife chorizo',
                    foto: '',
                    desc: 'Sandwich bife chorizo',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Choripan',
                    foto: '',
                    desc: 'Choripan',
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Pollo crispa',
                    foto: '',
                    desc: 'Pollo crispa',
                    precio: '$$$$',
                },
            ],
            acompañamientos: [
                {
                    id: 0,
                    nombre: 'Papas 1',
                    foto: '',
                    desc: 'Descripcion papas 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Papas 2',
                    foto: '',
                    desc: 'Descripcion papas 2',
                    precio: '$$$$',
                },
            ],
            bebidas: [shared.gaseosas, shared.agua_mineral],
        },
    },
    {
        id: 1,
        cerveceria: true,
        nombre: 'Garinger',
        foto: '',
        desc: 'Cerveza Artesanal',
        userInsta: '',
        idFace: '',
        numWpp: '',
        carta: {
            cervezas: [
                {
                    id: 0,
                    nombre: 'Cerveza 1',
                    foto: '',
                    desc: 'Descripcion cerveza 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Cerveza 2',
                    foto: '',
                    desc: 'Descripcion cerveza 2',
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Cerveza 3',
                    foto: '',
                    desc: 'Descripcion cerveza 3',
                    precio: '$$$$',
                },
            ],
        },
    },
    {
        id: 2,
        nombre: 'Station',
        foto: '',
        desc: 'Panchos y Ciabatta',
        userInsta: '',
        idFace: '',
        numWpp: '',
        carta: {
            principales: [
                {
                    id: 0,
                    nombre: 'Pancho 1',
                    foto: '',
                    desc: 'Descripcion pancho 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Pancho 2',
                    foto: '',
                    desc: 'Descripcion pancho 2',
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Ciabatta',
                    foto: '',
                    desc: 'Descripcion ciabatta',
                    precio: '$$$$',
                },
            ],
            acompañamientos: [
                {
                    id: 0,
                    nombre: 'Papas 1',
                    foto: '',
                    desc: 'Descripcion papas 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Papas 2',
                    foto: '',
                    desc: 'Descripcion papas 2',
                    precio: '$$$$',
                },
            ],
            bebidas: [shared.gaseosas, shared.agua_mineral],
        },
    },
    {
        id: 3,
        nombre: 'Sapore Di Famiglia',
        foto: sapore.logo,
        desc: 'Pastas Caseras',
        userInsta: '_saporedifamiglia_',
        idFace: '',
        numWpp: [5492664020989, 5492664173795],
        carta: {
            sorrentinos: [
                {
                    id: 0,
                    nombre: 'Muzarella y jamon',
                    foto: sapore.sorrentinos1,
                    desc: 'Sorrentinos de Muzarella y jamon',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Muzarella, tomate y albahaca',
                    foto: sapore.sorrentinos2,
                    desc: 'Sorrentinos de Muzarella, tomate y albahaca',
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Muzarella y cantimpalo',
                    foto: sapore.sorrentinos3,
                    desc: 'Sorrentinos de Muzarella y cantimpalo',
                    precio: '$$$$',
                },
                {
                    id: 3,
                    nombre: 'Muzarella, rucula y jamon crudo',
                    foto: sapore.sorrentinos4,
                    desc: 'Sorrentinos de Muzarella, rucula y jamon crudo',
                    precio: '$$$$',
                },
            ],
            raviolones: [
                {
                    id: 0,
                    nombre: 'Muzarella, verdeo y panceta',
                    foto: sapore.raviolones1,
                    desc: 'Raviolones de Muzarella, verdeo y panceta',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Cuatro quesos',
                    foto: sapore.raviolones2,
                    desc: 'Raviolones de Cuatro quesos',
                    precio: '$$$$',
                },
            ],
            ñoquis: [
                {
                    id: 0,
                    nombre: 'De papa',
                    foto: sapore.ñoquisTricolor,
                    desc: 'Ñoquis de papa',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Tricolor',
                    foto: sapore.ñoquisTricolor,
                    desc: 'Ñoquis tricolor',
                    precio: '$$$$',
                },
            ],
            tallarines: [
                {
                    id: 0,
                    nombre: 'Tallarines',
                    foto: sapore.tallarines,
                    desc: 'Tallarines',
                    precio: '$$$$',
                },
            ],
            salsas: [
                {
                    id: 0,
                    nombre: 'Salsa 1',
                    foto: sapore.sorrentinos1,
                    desc: 'Descripcion salsa 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Salsa 2',
                    foto: sapore.sorrentinos2,
                    desc: 'Descripcion salsa 2',
                    precio: '$$$$',
                },
            ],
            bebidas: [
                shared.gaseosas,
                shared.agua_mineral,
                {
                    id: 2,
                    nombre: 'Vino 1',
                    foto: sapore.vino,
                    desc: 'Consultar variedades',
                    precio: '$$$$',
                },
            ],
        },
    },
    {
        id: 4,
        nombre: 'Berraco',
        foto: berraco.logo,
        desc: 'Lomitos y Milanesas',
        userInsta: '',
        idFace: '',
        numWpp: '',
        carta: {
            lomitos: [
                {
                    id: 0,
                    nombre: 'Lomito Simple',
                    foto: berraco.lomito,
                    desc: 'Pan artesanal, Carne vacuna, Queso, Tomate, Lechuga y Papas Fritas. Aderezos a elección',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Lomito Full',
                    foto: berraco.lomitoRecortado,
                    desc: 'Pan artesanal, Carne vacuna, Queso, Jamón, Tomate, Lechuga, Huevo y Papas Fritas. Aderezos a elección',
                    precio: '$$$$',
                },
            ],
            milanesas: [
                {
                    id: 0,
                    nombre: 'Sandwich Milanesa simple',
                    foto: berraco.milanesa,
                    desc: 'Pan artesanal, Milanesa de ternera, Queso, Jamón, Tomate, Lechuga y Papas Fritas. Aderezos a elección',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Sandwich Milanesa Full',
                    foto: berraco.milanesaRecortada,
                    desc: 'Pan artesanal, Milanesa de ternera, Queso, Jamón, Tomate, Lechuga, Huevo y Papas fritas. Aderezos a elección',
                    precio: '$$$$',
                },
            ],
            veggie: [
                {
                    id: 0,
                    nombre: 'Sandwich Veggie',
                    foto: berraco.veggieRecortada,
                    desc: 'Pan Integral, Milanesa de Garbanzo, Queso, Palta, Berenjena, Tomate, Lechuga y Mayonesa vegetal de Zanahoria y Calabaza',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Opcional Vegano',
                    foto: '',
                    desc: 'Sandwich Veggie opcional vegano ',
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Adicional Huevo',
                    foto: '',
                    desc: 'Sandwich Veggie adicional huevo',
                    precio: '$$$$',
                },
                {
                    id: 3,
                    nombre: 'Adicional Papas',
                    foto: '',
                    desc: 'Sandwich Veggie adicional papas',
                    precio: '$$$$',
                },
            ],
            papas_fritas: [
                {
                    id: 0,
                    nombre: 'Cono',
                    foto: berraco.papasFritas,
                    desc: 'Cono de papas',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Bandeja',
                    foto: berraco.papasFritas,
                    desc: 'Bandeja de papas',
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Bandeja Salseada',
                    foto: berraco.papasFritas,
                    desc: 'Cheddar, Bacon y Verdeo',
                    precio: '$$$$',
                },
            ],
            bebidas: [
                shared.gaseosas,
                shared.agua_mineral,
                {
                    id: 2,
                    nombre: 'Fernet Cola',
                    foto: '',
                    desc: 'Fernet branca con cola',
                    precio: '$$$$',
                },
            ],
        },
    },
    {
        id: 5,
        nombre: 'Buena Faena',
        foto: '',
        desc: 'Pulled Pork y Hamburguesas Gourmet',
        userInsta: '',
        idFace: '',
        numWpp: '',
        carta: {
            hamburguesas: [
                {
                    id: 0,
                    nombre: 'Gourmet',
                    foto: '',
                    desc: 'Descripcion hamburguesa gourmet',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Pork',
                    foto: '',
                    desc: 'Descripcion hamburguesa pork',
                    precio: '$$$$',
                },
            ],
            hotdogs: [
                {
                    id: 0,
                    nombre: 'Chucrut',
                    foto: '',
                    desc: 'Descripcion hotdog chucrut',
                },
            ],
            bebidas: [
                {
                    id: 0,
                    nombre: 'Gaseosa',
                    foto: '',
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Agua Mineral',
                    foto: '',
                    desc: 'Linea Pepsi',
                    precio: '$$$$',
                },
            ],
        },
    },
    {
        id: 6,
        cerveceria: true,
        nombre: 'Chunkana',
        foto: '',
        desc: 'Cerveza Artesanal',
        userInsta: '',
        idFace: '',
        numWpp: '',
        carta: {
            cerveza: [
                {
                    id: 0,
                    nombre: 'Cerveza 1',
                    foto: '',
                    desc: 'Descripcion cerveza 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Cerveza 2',
                    foto: '',
                    desc: 'Descripcion cerveza 2',
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Cerveza 3',
                    foto: '',
                    desc: 'Descripcion cerveza 3',
                    precio: '$$$$',
                },
            ],
        },
    },
    {
        id: 7,
        nombre: 'El Bululu',
        foto: elBululu.logo,
        desc: `Comida Venezolana y Helado Soft`,
        userInsta: 'elbululu.ve',
        idFace: '',
        numWpp: [5492664848269, 5491154579188],
        carta: {
            arepas: [
                {
                    id: 0,
                    nombre: 'Mechada',
                    foto: elBululu.arepas1,
                    desc: 'Arepa hecha con harina de maíz sin TACC, con relleno de carne desmenuzada con queso',
                    precio: '$$$$$$',
                },
                {
                    id: 1,
                    nombre: 'Reina pepiada',
                    foto: elBululu.arepas2,
                    desc: 'Arepa hecha con harina de maíz sin TACC, con relleno de pollo desmenuzado con aderezo de palta y queso',
                    precio: '$$$$$$',
                },
                {
                    id: 2,
                    nombre: 'Pollo al Grill',
                    foto: elBululu.arepas3,
                    desc: 'Arepa hecha con harina de maíz sin TACC, con relleno de pollo a la plancha con jamón y queso',
                    precio: '$$$$$$',
                },
                {
                    id: 3,
                    nombre: 'Veggie',
                    foto: elBululu.arepas1,
                    desc: 'Arepa hecha con harina de maíz sin TACC, con relleno de vegetales salteados y queso',
                    precio: '$$$$$$',
                },
            ],
            tequeños: [
                {
                    id: 0,
                    nombre: 'Queso',
                    foto: elBululu.tequeños1,
                    desc: 'deditos de queso blanco envueltos en harina de trigo',
                    precio: '$$$$$$',
                },
                {
                    id: 1,
                    nombre: 'Chocolate',
                    foto: elBululu.tequeños2,
                    desc: 'deditos de chocolate envueltos en harina de trigo',
                    precio: '$$$$$$',
                },
            ],
            bebidas: [shared.gaseosas, shared.agua_mineral],
        },
    },
    {
        id: 8,
        nombre: 'La Patrona',
        foto: patrona.logo,
        desc: 'Comida Mexicana',
        userInsta: '',
        idFace: '',
        numWpp: '',
        carta: {
            tacos: [
                {
                    id: 0,
                    nombre: 'Carne',
                    foto: '',
                    desc: 'Descripcion tacos carne',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Veggie',
                    foto: '',
                    desc: 'Descripcion tacos veggie',
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Quesadillas',
                    foto: '',
                    desc: 'Descripcion quesadillas',
                    precio: '$$$$',
                },
            ],
            acompañamientos: [
                {
                    id: 0,
                    nombre: 'Nachos',
                    foto: '',
                    desc: 'Descripcion nachos',
                    precio: '$$$$',
                },
            ],
            bebidas: [shared.gaseosas, shared.agua_mineral],
        },
    },
    {
        id: 9,
        nombre: 'Poppi',
        foto: '',
        desc: 'Pizzas y Empanadas',
        userInsta: '',
        idFace: '',
        numWpp: '',
        carta: {
            pizzas: [
                {
                    id: 0,
                    nombre: 'Napolitana',
                    foto: poppi.pizza1,
                    desc: 'Pizza de napolitana',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Roquefort',
                    foto: poppi.pizza2,
                    desc: 'Pizza de roquefort',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Anchoas',
                    foto: poppi.pizza3,
                    desc: 'Pizza de anchoas',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Huevo',
                    foto: poppi.pizza1,
                    desc: 'Pizza de huevo',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Jamon y morron',
                    foto: poppi.pizza2,
                    desc: 'Pizza de Jamon y morron',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Vegetales',
                    foto: poppi.pizza3,
                    desc: 'Pizza de Vegetales',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Rúcula',
                    foto: poppi.pizza1,
                    desc: 'Pizza de Rúcula',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Champiñones',
                    foto: poppi.pizza2,
                    desc: 'Pizza de Champiñones',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Calabresa',
                    foto: poppi.pizza3,
                    desc: 'Pizza de Calabresa',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Palmitos',
                    foto: poppi.pizza1,
                    desc: 'Pizza de Palmitos',
                    precio: '$$$$',
                },
            ],
            empanadas: [
                {
                    id: 0,
                    nombre: 'Carne',
                    foto: poppi.empanadas1,
                    desc: 'Descripcion Carne',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Pollo',
                    foto: poppi.empanadas1,
                    desc: 'Descripcion Pollo',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Capresse',
                    foto: poppi.empanadas1,
                    desc: 'Descripcion Capresse',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Jamón y queso',
                    foto: poppi.empanadas1,
                    desc: 'Descripcion Jamón y queso',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Vegetales',
                    foto: poppi.empanadas1,
                    desc: 'Descripcion Vegetales',
                    precio: '$$$$',
                },
            ],
            ensaladas: [
                {
                    id: 0,
                    nombre: 'Ensalada 1',
                    foto: '',
                    desc: 'Descripcion Ensalada 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Ensalada 2',
                    foto: '',
                    desc: 'Descripcion Ensalada 2',
                    precio: '$$$$',
                },
            ],
            papas: [
                {
                    id: 0,
                    nombre: 'Papas 1',
                    foto: '',
                    desc: 'Descripcion Papas 1',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Papas 2',
                    foto: '',
                    desc: 'Descripcion Papas 2',
                    precio: '$$$$',
                },
            ],
            postres: [
                {
                    id: 0,
                    nombre: 'Tiramisu',
                    foto: '',
                    desc: 'Descripcion Tiramisu',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Chocotorta',
                    foto: '',
                    desc: 'Descripcion Chocotorta',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Cheesecake',
                    foto: '',
                    desc: 'Descripcion Cheesecake',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Flan casero',
                    foto: '',
                    desc: 'Descripcion Flan casero',
                    precio: '$$$$',
                },
            ],
            bebidas: [shared.gaseosas, shared.agua_mineral],
        },
    },
    {
        id: 10,
        nombre: 'Dulzuras Detuti',
        foto: detuti.logoColor,
        desc: 'Garrapiñadas y Turrones',
        userInsta: '',
        idFace: '',
        numWpp: '',
        carta: {
            garrapiñadas: [
                {
                    id: 0,
                    nombre: 'Garrapiñada Mani',
                    foto: '',
                    desc: 'Descripcion garrapiñada Mani',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Garrapiñada Girasol',
                    foto: '',
                    desc: 'Descripcion garrapiñada girasol',
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Garrapiñada Nuez',
                    foto: '',
                    desc: 'Descripcion garrapiñada Nuez',
                    precio: '$$$$',
                },
                {
                    id: 3,
                    nombre: 'Garrapiñada Almendra',
                    foto: '',
                    desc: 'Descripcion garrapiñada Almendra',
                    precio: '$$$$',
                },
                {
                    id: 4,
                    nombre: 'Garrapiñada Castañas de Caju',
                    foto: '',
                    desc: 'Descripcion garrapiñada Castañas de Caju',
                    precio: '$$$$',
                },
                {
                    id: 5,
                    nombre: 'Garrapiñada Avellana',
                    foto: '',
                    desc: 'Descripcion garrapiñada Avellana',
                    precio: '$$$$',
                },
            ],
            turrones_blandos: [
                {
                    id: 0,
                    nombre: 'Mani triturado',
                    foto: '',
                    desc: 'Descripcion Mani triturado',
                    precio: '$$$$',
                },
                {
                    id: 1,
                    nombre: 'Mani y Coco Rallado',
                    foto: '',
                    desc: 'Descripcion Mani y Coco Rallado',
                    precio: '$$$$',
                },
                {
                    id: 2,
                    nombre: 'Mani y Chocolate Rallado',
                    foto: '',
                    desc: 'Descripcion Mani y Chocolate Rallado',
                    precio: '$$$$',
                },
            ],
        },
    },
]

export default dataCarritos
